Repository lnbook/lnbook, pull requests merged in 2021-07, with the labels that each got.

#727 WIP: Channel Operation chapter release prep
  09_channel_operation.asciidoc
  README.md
  channel-operation.asciidoc
  images/HTLC_commitment_message_flow_1.png
  images/LN_protocol_channelops_highlight.png
  images/add_commitment_3a.png
  images/add_commitment_3b.png
  images/alice_bob_commitment_txs_1.png
  images/alice_bob_htlc_fulfilled.png
  images/htlc_fulfillment_commitments_added.png
  images/htlc_fulfillment_commitments_bob_commit.png
  images/htlc_fulfillment_message_flow.png
  images/revoked_commitment_2a.png
  images/revoked_commitment_2b.png
  images/signed_commitment_3a.png
  images/signed_commitment_3b.png
Labels: WIP

#736 Onion routing chapter release prep
  09_channel_operation.asciidoc
  10_onion_routing.asciidoc
  README.md
  appendix_failure_types.asciidoc
  contrib/old_onion_routing_draft.asciidoc
  failure_types_table.asciidoc
  images/LN-protocol-onion-highlight.png
  images/alice_dina_path.png
  images/alice_dina_path_detail.png
  images/bob_deobfuscates.png
  images/bob_envelope.png
  images/bob_extends.png
  images/bob_extends_deobfuscates.png
  images/bob_onion_payload.png
  images/bob_onion_wrapping.png
  images/bob_removes_shifts.png
  images/chan_envelope.png
  images/chan_onion_payload.png
  images/chan_onion_wrapping.png
  images/dina_envelope.png
  images/dina_hop_payload_hmac.png
  images/dina_onion_payload.png
  images/dina_onion_wrapping.png
  images/nested_envelopes.png
  images/onion_add_dina.png
  images/onion_hop_payloads.png
  images/onion_keygen.png
  images/onion_obfuscate_dina.png
  images/onion_packet.png
  images/onion_payload_filler.png
  images/sending_nested_envelopes.png
  tools/update_failure_types.py
Labels: need-fact-check

#734 Providing not proving
  05_node_operations.asciidoc
Labels: needs rebase
