Repository lnbook/lnbook, pull requests merged in 2021-09, with the labels that each got.

#837 Update the c-lightning installation instructions and make things a bit more stable
  04_node_client.asciidoc
  code/docker/bitcoind/bitcoind-entrypoint.sh
  code/docker/c-lightning/Dockerfile
  code/docker/c-lightning/devkeys.pem
  code/docker/c-lightning/fund-c-lightning.sh
Labels: NeededForDelivery

#694 minor glossary updates for consistency
  glossary.asciidoc
Labels: decision pending

#726 typo
  03_how_ln_works.asciidoc
Labels: needs rebase
